pub mod auth;
#[cfg(feature = "static-frontend")]
pub mod frontend;
#[cfg(feature = "graphql")]
pub mod graphql;
pub mod ir;
#[cfg(feature = "mcp")]
pub mod mcp;
pub mod migration;
pub mod query;
pub mod rbac;
pub mod resource;
pub mod rest;
pub mod users;
